BEGIN;

CREATE EXTENSION IF NOT EXISTS pgtap WITH SCHEMA extensions;
SET search_path = public, extensions;

SELECT plan(3);

CREATE FUNCTION public.dev_1132_default_function_probe()
RETURNS boolean
LANGUAGE sql
AS $$ SELECT true $$;

CREATE TABLE public.dev_1132_default_table_probe (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);
ALTER TABLE public.dev_1132_default_table_probe ENABLE ROW LEVEL SECURITY;

CREATE SEQUENCE public.dev_1132_default_sequence_probe;

SELECT is_empty(
  $$
    SELECT role_name
    FROM unnest(ARRAY['PUBLIC', 'anon', 'authenticated', 'service_role']) AS role_name
    WHERE pg_catalog.has_function_privilege(
      role_name,
      'public.dev_1132_default_function_probe()',
      'EXECUTE'
    )
  $$,
  'new public functions receive no implicit Data API execute grants'
);

SELECT is_empty(
  $$
    SELECT role_name || ':' || privilege_name
    FROM unnest(ARRAY['anon', 'authenticated', 'service_role']) AS role_name
    CROSS JOIN unnest(ARRAY[
      'SELECT',
      'INSERT',
      'UPDATE',
      'DELETE',
      'TRUNCATE',
      'REFERENCES',
      'TRIGGER'
    ]) AS privilege_name
    WHERE pg_catalog.has_table_privilege(
      role_name,
      'public.dev_1132_default_table_probe',
      privilege_name
    )
  $$,
  'new public tables receive no implicit Data API grants'
);

SELECT is_empty(
  $$
    SELECT role_name || ':' || privilege_name
    FROM unnest(ARRAY['anon', 'authenticated', 'service_role']) AS role_name
    CROSS JOIN unnest(ARRAY['USAGE', 'SELECT', 'UPDATE']) AS privilege_name
    WHERE pg_catalog.has_sequence_privilege(
      role_name,
      'public.dev_1132_default_sequence_probe',
      privilege_name
    )
  $$,
  'new public sequences receive no implicit Data API grants'
);

SELECT * FROM finish();
ROLLBACK;
