-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgm+m0mE+mx7KpbEEf
ixL3MsXP+v1QUIV+YvgutLqvE7KgCgYIKoZIzj0DAQehRANCAASVz8gR2FoQPHXe
Wc2HrBuy+0dvh0Q9gaTOWeSdayM3IMBeSEQrblhO464wBSoyG6gzXiuklKmeNSK+
o3Ft16qT
-----END PRIVATE KEY-----